### ISSUE TITLE
Nullable issues with Gu.Roslyn.Extensions.Source

### ISSUE THREAD

**Issue by GeertvanHorrik** [GuOrg/Gu.Roslyn.Extensions#147]
I am trying to use 0.16.1, but get a few more compilation errors:

```
1>C:\Users\username\.nuget\packages\gu.roslyn.extensions.source\0.16.1\contentFiles\cs\any\AnalyzerExtensions\EnumerableExt.generated.cs(222,22,222,38): error CS8601: Possible null reference assignment.
1>C:\Users\username\.nuget\packages\gu.roslyn.extensions.source\0.16.1\contentFiles\cs\any\AnalyzerExtensions\EnumerableExt.generated.cs(578,22,578,38): error CS8601: Possible null reference assignment.
1>C:\Users\username\.nuget\packages\gu.roslyn.extensions.source\0.16.1\contentFiles\cs\any\AnalyzerExtensions\EnumerableExt.generated.cs(1063,22,1063,38): error CS8625: Cannot convert null literal to non-nullable reference type.
1>C:\Users\username\.nuget\packages\gu.roslyn.extensions.source\0.16.1\contentFiles\cs\any\AnalyzerExtensions\EnumerableExt.generated.cs(1402,22,1402,38): error CS8625: Cannot convert null literal to non-nullable reference type.
```

![image](https://user-images.githubusercontent.com/1246444/142986292-13477869-1ac3-4ba3-9bc9-de801236f824.png)

**Comment by JohanLarsson** [comment]
You have warnings as errors enabled?

It is unfortunate that Roslyn decides to check the source from the package, no way to disable the check. We tried adding an .editorconfig to the source package that disabled all checks but tooling ignored it.

Now we have a build task that adds:
```cs
// <auto-generated/>
#nullable enable
```
 to every file in the package but we still get those warnings, not much fun.
 Thanks you for reporting though, must try to find a fix.

**Comment by JohanLarsson** [comment]
Found one issue now, the code in your screenshot is generated by T4 and missing the explicit `#nullable enable`  that is needed in generated code.

**Comment by JohanLarsson** [comment]
Found another issue, missing `[MaybeNullWhen(false)]` in that method. Releasing new package now.

**Comment by JohanLarsson** [comment]
https://www.nuget.org/packages/Gu.Roslyn.Extensions.Source/0.16.2

**Comment by GeertvanHorrik** [comment]
Works like a charm, releasing hotfixes for 2 analyzers now.

Thanks for your support!
