### ISSUE TITLE
Upgrade dependency for Microsoft.CodeAnalysis.CSharp.Workspaces

### ISSUE THREAD

**Issue by klemmchr** [GuOrg/Gu.Roslyn.Extensions#165]
Currently the dependency on `Microsoft.CodeAnalysis.CSharp.Workspaces` for version `4.0.1` prevents me from upgrading `Microsoft.CodeAnalysis.CSharp` to `4.1.0`. Could it be possible to upgrade this package requirement?

![image](https://user-images.githubusercontent.com/6552521/161506604-8ba6bd4a-91c9-4c72-856c-1ba157b0cc05.png)

**Comment by JohanLarsson** [comment]
Are you using the source package?
Prefer the source package as it works around many bugs in MSFT tooling.
The source package should not know about Roslyn version.

**Comment by JohanLarsson** [comment]
https://www.nuget.org/packages/Gu.Roslyn.Extensions.Source/

It is a nuget containing the source code  of this library.

**Comment by JohanLarsson** [comment]
hmm,
[Microsoft.CodeAnalysis.CSharp.Workspaces](https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp.Workspaces/) (>= 4.0.1)

Should allow setting a higher version in consuming project I think, wonder what the issue is.

**Comment by klemmchr** [comment]
I don't understand it either but you could specify a version range like `[4.0,5.0)` to achieve the version constraint `4.0 ≤ x < 5.0`

**Comment by JohanLarsson** [comment]
https://www.nuget.org/packages/Gu.Roslyn.Extensions.Source/0.17.0

Hopefully that works
